language: python
sudo: false
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install: pip install .
before_script:
  - pip install -r tests/requirements.txt
script:  coverage run --source=django_wsgi setup.py test
after_success:
  - coveralls
